language: bash

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin 

install:
    docker build --no-cache -t somrc/bart-web:latest . ;
    docker push somrc/bart-web:latest;

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - nmagee@virginia.edu
